source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

target 'Hello-Lynx' do
  pod 'Lynx', '3.5.1', :subspecs => [
    'Framework',
  ]


  # integrate image-service, log-service, and http-service
  pod 'LynxService', '3.5.1', :subspecs => [
      'Image',
      'Log',
      'Http',
  ]

  # ImageService dependencies:
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'

  # XElement
  pod 'XElement', '3.5.1'
end