plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.jetbrains.kotlin.android)
}

android {
    namespace = "com.lynx.levl"
    compileSdk = 34
    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        applicationId = "com.lynx.kotlinemptyproject"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        debug {
            buildConfigField(
                "String",
                "LYNX_DEV_BUNDLE_URL",
                "\"http://192.168.1.2:3000/main.lynx.bundle\"" // 模拟器用 10.0.2.2，真机用你电脑局域网 IP
            )
        }
        release {
                buildConfigField(
                    "String",
                    "LYNX_DEV_BUNDLE_URL",
                    "\"\""
                )
//            isMinifyEnabled = false
//            proguardFiles(
//                getDefaultProguardFile("proguard-android-optimize.txt"),
//                "proguard-rules.pro"
//            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.1"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)

    // lynx dependencies
    implementation("org.lynxsdk.lynx:lynx:3.5.1")
    implementation("org.lynxsdk.lynx:lynx-jssdk:3.5.1")
    implementation("org.lynxsdk.lynx:lynx-trace:3.5.1")
    implementation("org.lynxsdk.lynx:primjs:2.15.1")

    // integrating image-service
    implementation("org.lynxsdk.lynx:lynx-service-image:3.5.1")

    // image-service dependencies, if not added, images cannot be loaded; if the host APP needs to use other image libraries, you can customize the image-service and remove this dependency
    implementation("com.facebook.fresco:fresco:2.3.0")
    implementation("com.facebook.fresco:animated-gif:2.3.0")
    implementation("com.facebook.fresco:animated-webp:2.3.0")
    implementation("com.facebook.fresco:webpsupport:2.3.0")
    implementation("com.facebook.fresco:animated-base:2.3.0")

    // integrating log-service
    implementation("org.lynxsdk.lynx:lynx-service-log:3.5.1")

    // integrating http-service
    implementation("org.lynxsdk.lynx:lynx-service-http:3.5.1")

    implementation("com.squareup.okhttp3:okhttp:4.9.0")

    // add devtool's dependencies
    implementation ("org.lynxsdk.lynx:lynx-devtool:3.5.1")
    implementation ("org.lynxsdk.lynx:lynx-service-devtool:3.5.1")

    // add xelement's dependencies
    implementation ("org.lynxsdk.lynx:xelement:3.5.1")
    implementation ("org.lynxsdk.lynx:xelement-input:3.5.1")
}
// GENERATED AUTOLINK DEPENDENCIES START
// This section is automatically generated by Tamer4Lynx.
    // Manual edits will be overwritten.
    // No native dependencies found to link.
// GENERATED AUTOLINK DEPENDENCIES END
